# Generated by Django 5.1.7 on 2025-03-13 12:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('vehicle_model', 'Модель техники'), ('engine_model', 'Модель двигателя'), ('transmission_model', 'Модель трансмиссии'), ('drive_axle_model', 'Модель ведущего моста'), ('steering_axle_model', 'Модель управляемого моста'), ('maintenance_type', 'Вид ТО'), ('failure_node', 'Узел отказа'), ('recovery_method', 'Способ восстановления')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CL', 'Клиент'), ('SO', 'Сервисная организация'), ('MA', 'Менеджер')], default='CL', max_length=2)),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=100, unique=True)),
                ('engine_number', models.CharField(max_length=100, unique=True)),
                ('transmission_number', models.CharField(max_length=100, unique=True)),
                ('drive_axle_number', models.CharField(max_length=100, unique=True)),
                ('steering_axle_number', models.CharField(max_length=100, unique=True)),
                ('supply_contract', models.CharField(max_length=100)),
                ('shipping_date', models.DateField()),
                ('buyer', models.CharField(max_length=100)),
                ('delivery_address', models.CharField(max_length=100)),
                ('equipment', models.TextField(default='Стандарт')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CL'}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
                ('drive_axle_model', models.ForeignKey(limit_choices_to={'reference_type': 'drive_axle_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='drive_axle_models', to='api.referencebook')),
                ('engine_model', models.ForeignKey(limit_choices_to={'reference_type': 'engine_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='engine_models', to='api.referencebook')),
                ('service', models.ForeignKey(limit_choices_to={'role': 'SO'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
                ('steering_axle_model', models.ForeignKey(limit_choices_to={'reference_type': 'steering_axle_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='steering_axle_models', to='api.referencebook')),
                ('transmission_model', models.ForeignKey(limit_choices_to={'reference_type': 'transmission_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='transmission_models', to='api.referencebook')),
                ('vehicle_model', models.ForeignKey(limit_choices_to={'reference_type': 'vehicle_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='api.referencebook')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField()),
                ('operating_time', models.IntegerField()),
                ('work_order_number', models.CharField(max_length=100, unique=True)),
                ('work_order_date', models.DateField()),
                ('service', models.ForeignKey(blank=True, limit_choices_to={'role': 'SO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_services', to=settings.AUTH_USER_MODEL)),
                ('maintenance_type', models.ForeignKey(limit_choices_to={'reference_type': 'maintenance_type'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='api.referencebook')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField()),
                ('operating_time', models.IntegerField()),
                ('failure_description', models.CharField(max_length=100)),
                ('spare_parts', models.CharField(max_length=100)),
                ('recovery_date', models.DateField()),
                ('downtime', models.IntegerField(editable=False)),
                ('service', models.ForeignKey(limit_choices_to={'role': 'SO'}, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_services', to=settings.AUTH_USER_MODEL)),
                ('failure_node', models.ForeignKey(limit_choices_to={'reference_type': 'failure_node'}, on_delete=django.db.models.deletion.CASCADE, related_name='failure_nodes', to='api.referencebook')),
                ('recovery_method', models.ForeignKey(limit_choices_to={'reference_type': 'recovery_method'}, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_methods', to='api.referencebook')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.vehicle')),
            ],
        ),
    ]
