# Generated by Django 5.1.7 on 2025-03-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='spare_parts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
