# Generated by Django 5.1.7 on 2025-03-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_complaint_spare_parts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='buyer',
            new_name='consignee',
        )
    ]
