# Generated by Django 5.1.7 on 2025-03-25 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250325_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'CL'}, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='consignee',
            field=models.CharField(max_length=100, verbose_name='Грузополучатель (конечный потребитель)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='delivery_address',
            field=models.CharField(max_length=100, verbose_name='Адрес поставки (эксплуатации)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_axle_model',
            field=models.ForeignKey(limit_choices_to={'reference_type': 'drive_axle_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='drive_axle_models', to='api.referencebook', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='drive_axle_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_model',
            field=models.ForeignKey(limit_choices_to={'reference_type': 'engine_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='engine_models', to='api.referencebook', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='equipment',
            field=models.TextField(default='Стандарт', verbose_name='Комплектация (доп. опции)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='factory_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='service',
            field=models.ForeignKey(limit_choices_to={'role': 'SO'}, on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='shipping_date',
            field=models.DateField(verbose_name='Дата отгрузки с завода'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='steering_axle_model',
            field=models.ForeignKey(limit_choices_to={'reference_type': 'steering_axle_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='steering_axle_models', to='api.referencebook', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='steering_axle_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='supply_contract',
            field=models.CharField(max_length=100, verbose_name='Договор поставки №, дата'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission_model',
            field=models.ForeignKey(limit_choices_to={'reference_type': 'transmission_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='transmission_models', to='api.referencebook', verbose_name='Модель трансмиссии'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Зав. № трансмиссии'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(limit_choices_to={'reference_type': 'vehicle_model'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_models', to='api.referencebook', verbose_name='Модель техники'),
        ),
    ]
