# Generated by Django 5.1.7 on 2025-03-25 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_vehicle_client_alter_vehicle_consignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='downtime',
            field=models.IntegerField(editable=False, verbose_name='Время простоя техники'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_date',
            field=models.DateField(verbose_name='Дата отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_description',
            field=models.CharField(max_length=100, verbose_name='Описание отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(limit_choices_to={'reference_type': 'failure_node'}, on_delete=django.db.models.deletion.CASCADE, related_name='failure_nodes', to='api.referencebook', verbose_name='Узел отказа'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='operating_time',
            field=models.IntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_date',
            field=models.DateField(verbose_name='Дата восстановления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(limit_choices_to={'reference_type': 'recovery_method'}, on_delete=django.db.models.deletion.CASCADE, related_name='recovery_methods', to='api.referencebook', verbose_name='Способ восстановления'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='service',
            field=models.ForeignKey(limit_choices_to={'role': 'SO'}, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_services', to=settings.AUTH_USER_MODEL, verbose_name='Cервисная компания'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='spare_parts',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Используемые запасные части'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.vehicle', verbose_name='Mашина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(limit_choices_to={'reference_type': 'maintenance_type'}, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='api.referencebook', verbose_name='Вид ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='operating_time',
            field=models.IntegerField(verbose_name='Наработка, м/час'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_services', to=settings.AUTH_USER_MODEL, verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='api.vehicle', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_date',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='№ заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='referencebook',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='referencebook',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='referencebook',
            name='reference_type',
            field=models.CharField(choices=[('vehicle_model', 'Модель техники'), ('engine_model', 'Модель двигателя'), ('transmission_model', 'Модель трансмиссии'), ('drive_axle_model', 'Модель ведущего моста'), ('steering_axle_model', 'Модель управляемого моста'), ('maintenance_type', 'Вид ТО'), ('failure_node', 'Узел отказа'), ('recovery_method', 'Способ восстановления')], max_length=20, verbose_name='Тип справочника'),
        ),
    ]
