# Generated by Django 5.1.7 on 2025-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_complaint_downtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='work_order_number',
            field=models.CharField(error_messages={'unique': 'Номер уже используется'}, max_length=100, unique=True, verbose_name='№ заказ-наряда'),
        ),
    ]
