# Generated by Django 5.1.7 on 2025-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_maintenance_work_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='drive_axle_number',
            field=models.CharField(error_messages={'unique': 'Номер уже используется'}, max_length=100, unique=True, verbose_name='Зав. № ведущего моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_number',
            field=models.CharField(error_messages={'unique': 'Номер уже используется'}, max_length=100, unique=True, verbose_name='Зав. № двигателя'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='factory_number',
            field=models.CharField(error_messages={'unique': 'Номер уже используется'}, max_length=100, unique=True, verbose_name='Зав. № машины'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='steering_axle_number',
            field=models.CharField(error_messages={'unique': 'Номер уже используется'}, max_length=100, unique=True, verbose_name='Зав. № управляемого моста'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission_number',
            field=models.CharField(error_messages={'unique': 'Номер уже используется'}, max_length=100, unique=True, verbose_name='Зав. № трансмиссии'),
        ),
    ]
